// Payment Component
// Generates UPI payment link and QR code for payment

import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useCart } from '../../context/CartContext';
import { useAuth } from '../../context/AuthContext';
import { paymentAPI, orderAPI } from '../../utils/api';
import './User.css';

const Payment = () => {
    const navigate = useNavigate();
    const location = useLocation();
    const { cart, getTotalAmount, clearCart } = useCart();
    const { user } = useAuth();
    const qrCanvasRef = useRef(null);

    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [upiLink, setUpiLink] = useState('');
    const [orderId, setOrderId] = useState('');
    const [splitCount, setSplitCount] = useState(1);
    const [totalAmount, setTotalAmount] = useState(0);
    const [perPersonAmount, setPerPersonAmount] = useState(0);
    const [qrCodeGenerated, setQrCodeGenerated] = useState(false);

    useEffect(() => {
        // Get split info from navigation state
        const state = location.state;
        if (state) {
            setSplitCount(state.splitCount || 1);
            const total = (state.totalAmount * 1.05).toFixed(2); // Including 5% tax
            setTotalAmount(parseFloat(total));
            setPerPersonAmount((total / (state.splitCount || 1)).toFixed(2));
        } else {
            // If no state, calculate from cart
            const total = (getTotalAmount() * 1.05).toFixed(2);
            setTotalAmount(parseFloat(total));
            setPerPersonAmount(total);
        }
    }, [location.state, getTotalAmount]);

    // Generate UPI link and create order
    useEffect(() => {
        if (cart.length > 0 && totalAmount > 0) {
            createOrderAndGenerateUPI();
        }
    }, [totalAmount]);

    // Render QR code to canvas when UPI link is ready
    useEffect(() => {
        if (upiLink) {
            renderQRCodeToCanvas(upiLink);
        }
    }, [upiLink]);

    const renderQRCodeToCanvas = (upiString) => {
        const canvas = document.getElementById('payment-qr-canvas');
        if (!canvas) return;

        // Load QRCode library dynamically if not already loaded
        if (!window.QRCode) {
            const script = document.createElement('script');
            script.src = 'https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';
            script.onload = () => {
                createCanvasQRCode(canvas, upiString);
            };
            document.head.appendChild(script);
        } else {
            createCanvasQRCode(canvas, upiString);
        }
    };

    const createCanvasQRCode = (canvas, text) => {
        // Create a temporary container for QRCode.js
        const tempDiv = document.createElement('div');
        tempDiv.style.display = 'none';
        document.body.appendChild(tempDiv);

        // Generate QR code
        const qr = new window.QRCode(tempDiv, {
            text: text,
            width: 250,
            height: 250,
            colorDark: "#000000",
            colorLight: "#ffffff",
            correctLevel: window.QRCode.CorrectLevel.H
        });

        // Wait for QR code to be generated, then copy to canvas
        setTimeout(() => {
            const qrImg = tempDiv.querySelector('img');
            if (qrImg && canvas) {
                const ctx = canvas.getContext('2d');
                ctx.clearRect(0, 0, canvas.width, canvas.height);
                ctx.drawImage(qrImg, 0, 0, 250, 250);
                setQrCodeGenerated(true);
            }
            document.body.removeChild(tempDiv);
        }, 100);
    };

    const createOrderAndGenerateUPI = async () => {
        try {
            setLoading(true);

            // Prepare order items
            const orderItems = cart.map(item => ({
                item_id: item._id,
                name: item.name,
                price: item.price,
                quantity: item.quantity
            }));

            // Create order
            const orderResponse = await orderAPI.createOrder({
                items: orderItems,
                total_amount: totalAmount,
                split_count: splitCount,
                table_number: new URLSearchParams(window.location.search).get('table') || null
            });

            const newOrderId = orderResponse.data.order_id;
            setOrderId(newOrderId);

            // Generate UPI link
            const upiResponse = await paymentAPI.generateUPI({
                amount: totalAmount,
                order_id: newOrderId,
                customer_name: user?.name || 'Customer'
            });

            setUpiLink(upiResponse.data.upi_link);

            // QR code will be generated by useEffect when upiLink updates

        } catch (err) {
            setError(err.response?.data?.error || 'Failed to generate payment link');
        } finally {
            setLoading(false);
        }
    };

    const handlePayNow = () => {
        if (!upiLink) {
            alert('Payment link not generated yet. Please wait.');
            return;
        }

        // Open UPI link (will open GPay/PhonePe/Paytm)
        window.location.href = upiLink;

        // Simulate payment success after 3 seconds (for demo)
        setTimeout(() => {
            handlePaymentSuccess();
        }, 3000);
    };

    const handlePaymentSuccess = async () => {
        try {
            // Update payment status
            if (orderId) {
                await orderAPI.updatePaymentStatus(orderId, 'success');
            }

            // Get table number from URL
            const params = new URLSearchParams(window.location.search);
            const tableNumber = params.get('table');

            // Prepare bill data
            const billData = {
                orderId: orderId,
                orderTime: new Date().toISOString(),
                items: cart,
                totalAmount: totalAmount,
                splitCount: splitCount,
                perPersonAmount: perPersonAmount,
                tableNumber: tableNumber,
                customerName: user?.name || 'Customer',
                customerPhone: user?.phone || ''
            };

            // Clear cart
            clearCart();

            // Navigate to bill page with data
            navigate('/bill', { state: billData });

        } catch (err) {
            console.error('Error updating payment status:', err);
            alert('Payment successful but failed to generate bill. Please contact support.');
        }
    };

    const handleCancel = () => {
        navigate('/cart');
    };

    if (cart.length === 0 && !orderId) {
        return (
            <div className="payment-container">
                <div className="empty-state">
                    <h2>No items to pay for</h2>
                    <button className="btn btn-primary" onClick={() => navigate('/menu')}>
                        Go to Menu
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="payment-container">
            <header className="payment-header">
                <h1>Payment</h1>
            </header>

            {error && <div className="error-message">{error}</div>}

            {loading ? (
                <div className="loading">
                    <div className="spinner"></div>
                    <p>Generating payment link...</p>
                </div>
            ) : (
                <>
                    {/* Order Summary */}
                    <div className="payment-summary">
                        <h2>Order Summary</h2>

                        <div className="order-items">
                            {cart.map(item => (
                                <div key={item._id} className="order-item">
                                    <span>{item.name} x {item.quantity}</span>
                                    <span>₹{item.price * item.quantity}</span>
                                </div>
                            ))}
                        </div>

                        <div className="payment-details">
                            <div className="detail-row">
                                <span>Total Amount (with tax):</span>
                                <span className="amount">₹{totalAmount}</span>
                            </div>

                            {splitCount > 1 && (
                                <>
                                    <div className="detail-row">
                                        <span>Split Between:</span>
                                        <span className="amount">{splitCount} people</span>
                                    </div>
                                    <div className="detail-row highlight">
                                        <span>Per Person:</span>
                                        <span className="amount">₹{perPersonAmount}</span>
                                    </div>
                                </>
                            )}
                        </div>
                    </div>

                    {/* UPI Payment Section with QR Code */}
                    <div className="upi-section">
                        <div className="payee-header">
                            <div className="payee-avatar">C</div>
                            <h2 className="payee-name">Chandru P</h2>
                        </div>

                        {/* QR Code Display */}
                        {qrCodeGenerated || upiLink ? (
                            <div className="qr-code-container">
                                <div className="qr-code-wrapper">
                                    {/* QR Code Canvas (hidden, used for generation) */}
                                    <div ref={qrCanvasRef} className="qr-code-canvas" style={{ display: 'none' }}></div>

                                    {/* Static QR Code Display */}
                                    <div className="qr-code-static">
                                        <div className="qr-code-image-wrapper">
                                            {/* QR Code generated dynamically */}
                                            <canvas id="payment-qr-canvas" width="250" height="250"></canvas>

                                            {/* Google Pay Logo Overlay */}
                                            <div className="qr-logo-overlay">
                                                <svg viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
                                                    <circle cx="24" cy="24" r="24" fill="white" />
                                                    <g transform="translate(8, 8)">
                                                        <circle cx="16" cy="16" r="16" fill="#fff" />
                                                        <path d="M16 4C9.37 4 4 9.37 4 16s5.37 12 12 12 12-5.37 12-12S22.63 4 16 4z" fill="#5f6368" />
                                                        <circle cx="16" cy="16" r="10" fill="white" />
                                                        <path d="M16 10l-2 3h4l-2-3z" fill="#fbbc04" />
                                                        <circle cx="16" cy="16" r="4" fill="#34a853" />
                                                        <path d="M12 13h8M12 16h8M12 19h8" stroke="#4285f4" stroke-width="1.5" stroke-linecap="round" />
                                                        <circle cx="16" cy="18" r="1.5" fill="#ea4335" />
                                                    </g>
                                                </svg>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="upi-id-display">
                                    <strong>UPI ID:</strong> chandrupalanisamyaids@okaxis
                                </div>
                                <p className="qr-instruction">
                                    Scan to pay with any UPI app
                                </p>
                            </div>
                        ) : (
                            <div className="qr-loading">
                                <div className="spinner"></div>
                                <p>Generating QR Code...</p>
                            </div>
                        )}

                        <div className="upi-info">
                            <p>Or click below to open UPI app directly</p>
                            <div className="upi-icons">
                                <span>📱 GPay</span>
                                <span>💳 PhonePe</span>
                                <span>💰 Paytm</span>
                            </div>
                        </div>

                        <button
                            className="btn-pay-now"
                            onClick={handlePayNow}
                            disabled={!upiLink}
                        >
                            💳 Open UPI App - Pay ₹{splitCount > 1 ? perPersonAmount : totalAmount}
                        </button>

                        <p className="payment-note">
                            After payment, click "Mark as Paid" below
                        </p>
                    </div>                    {/* Action Buttons */}
                    <div className="payment-actions">
                        <button className="btn btn-outline" onClick={handleCancel}>
                            ← Back to Cart
                        </button>
                        <button className="btn btn-success" onClick={handlePaymentSuccess}>
                            ✓ Mark as Paid (Demo)
                        </button>
                    </div>
                </>
            )}
        </div>
    );
};

export default Payment;
